--This file contains the database data creation scripts, these scripts ARE NOT THE ORIGINAL.
--These scripts are generated by SQL Server, after the data was already inserted into the tables, so use these insert statements
--when/if we need to restart the whole database, it will be much faster than trying recreate the database from scratch.

--Seller Table:
USE [INFO2410_601_RMN_AutoSale_DatabaseMasters]
GO
SET IDENTITY_INSERT [dbo].[Seller] ON 
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1101, N'Browsebug', N'Summit', N'Huntington', N'WV', N'47919', N'fmarin0@sitemeter.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1103, N'Dazzlesphere', N'David', N'Charlotte', N'NC', N'20774', N'siacovacci2@cbsnews.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1104, N'Tagcat', N'Orin', N'El Paso', N'TX', N'61531', N'cblissett3@geocities.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1106, N'LiveZ', N'Carey', N'Boston', N'MA', N'17913', N'btremeer5@dyndns.org')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1107, N'Feednation', N'Meadow Ridge', N'Pittsburgh', N'PA', N'75246', N'ryerbury6@reverbnation.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1108, N'Camido', N'Hoffman', N'Kansas City', N'MO', N'78676', N'amays7@wikispaces.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1110, N'Quimm', N'Burrows', N'Washington', N'DC', N'68727', N'lferreras9@sourceforge.net')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1111, N'Roombo', N'Oxford', N'Trenton', N'NJ', N'34053', N'jzannettia@ucsd.edu')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1112, N'Trunyx', N'Gina', N'Washington', N'DC', N'22651', N'pguyetb@spiegel.de')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1113, N'Twinder', N'Lyons', N'Pittsburgh', N'PA', N'46249', N'traggittc@skyrock.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1115, N'Skinte', N'Dottie', N'Philadelphia', N'PA', N'74408', N'cgeeree@cnet.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1116, N'Photofeed', N'Westerfield', N'Miami', N'FL', N'84639', N'nfigiovannif@msn.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1117, N'Tazz', N'Ronald Regan', N'Beaufort', N'SC', N'34928', N'farnullg@about.me')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1119, N'Dazzlesphere', N'Southridge', N'Des Moines', N'IA', N'99443', N'ptimbridgei@webmd.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1120, N'Agimba', N'Nelson', N'Reno', N'NV', N'30347', N'ngoskarj@studiopress.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1121, N'Flipstorm', N'Northport', N'Fresno', N'CA', N'23242', N'cgillittk@opera.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1125, N'Rhyzio', N'Mallory', N'Knoxville', N'TN', N'88462', N'kalexandreo@chronoengine.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1126, N'Photofeed', N'Spaight', N'Saint Louis', N'MO', N'37845', N'bcobleighp@slate.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1127, N'Dablist', N'Tennyson', N'Austin', N'TX', N'52510', N'wkempstoneq@facebook.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1128, N'Wikivu', N'Golf', N'Shreveport', N'LA', N'74767', N'kfaunchr@dmoz.org')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1129, N'Mynte', N'Stang', N'Lake Charles', N'LA', N'39989', N'dmolans@de.vu')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1135, N'Skinix', N'1st', N'Columbia', N'SC', N'16541', N'aburniey@nbcnews.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1139, N'Flashset', N'Maryland', N'Anniston', N'AL', N'29361', N'afrenzl12@multiply.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1141, N'Twitterwire', N'Menomonie', N'Hartford', N'CT', N'82706', N'jstockoe14@godaddy.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1143, N'Twimbo', N'Barnett', N'Bronx', N'NY', N'85856', N'nburton16@economist.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1144, N'Photolist', N'Bowman', N'San Francisco', N'CA', N'96094', N'kmarion17@buzzfeed.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1145, N'Youfeed', N'Eastwood', N'New Brunswick', N'NJ', N'99091', N'tscrooby18@i2i.jp')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1148, N'Flashdog', N'Elka', N'Montpelier', N'VT', N'19033', N'wloomis1b@telegraph.co.uk')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1149, N'Dynazzy', N'Monterey', N'Kansas City', N'MO', N'69343', N'rmckerley1c@eepurl.com')
GO
INSERT [dbo].[Seller] ([seller_id], [seller_name], [Street], [City], [State], [ZIP], [Email]) VALUES (1150, N'Lazzy', N'New Castle', N'Augusta', N'GA', N'35964', N'kcrebott1d@cargocollective.com')
GO
SET IDENTITY_INSERT [dbo].[Seller] OFF
GO
